export type ArxivCategory = {
  code: string;
  group: string;
  name: string;
};

// Source: https://arxiv.org/category_taxonomy
export const ARXIV_CATEGORIES: ArxivCategory[] = [
  { code: "cs.AI", group: "Computer Science", name: "Artificial Intelligence" },
  { code: "cs.AR", group: "Computer Science", name: "Hardware Architecture" },
  { code: "cs.CC", group: "Computer Science", name: "Computational Complexity" },
  { code: "cs.CE", group: "Computer Science", name: "Computational Engineering, Finance, and Science" },
  { code: "cs.CG", group: "Computer Science", name: "Computational Geometry" },
  { code: "cs.CL", group: "Computer Science", name: "Computation and Language" },
  { code: "cs.CR", group: "Computer Science", name: "Cryptography and Security" },
  { code: "cs.CV", group: "Computer Science", name: "Computer Vision and Pattern Recognition" },
  { code: "cs.CY", group: "Computer Science", name: "Computers and Society" },
  { code: "cs.DB", group: "Computer Science", name: "Databases" },
  { code: "cs.DC", group: "Computer Science", name: "Distributed, Parallel, and Cluster Computing" },
  { code: "cs.DL", group: "Computer Science", name: "Digital Libraries" },
  { code: "cs.DM", group: "Computer Science", name: "Discrete Mathematics" },
  { code: "cs.DS", group: "Computer Science", name: "Data Structures and Algorithms" },
  { code: "cs.ET", group: "Computer Science", name: "Emerging Technologies" },
  { code: "cs.FL", group: "Computer Science", name: "Formal Languages and Automata Theory" },
  { code: "cs.GL", group: "Computer Science", name: "General Literature" },
  { code: "cs.GR", group: "Computer Science", name: "Graphics" },
  { code: "cs.GT", group: "Computer Science", name: "Computer Science and Game Theory" },
  { code: "cs.HC", group: "Computer Science", name: "Human-Computer Interaction" },
  { code: "cs.IR", group: "Computer Science", name: "Information Retrieval" },
  { code: "cs.IT", group: "Computer Science", name: "Information Theory" },
  { code: "cs.LG", group: "Computer Science", name: "Machine Learning" },
  { code: "cs.LO", group: "Computer Science", name: "Logic in Computer Science" },
  { code: "cs.MA", group: "Computer Science", name: "Multiagent Systems" },
  { code: "cs.MM", group: "Computer Science", name: "Multimedia" },
  { code: "cs.MS", group: "Computer Science", name: "Mathematical Software" },
  { code: "cs.NA", group: "Computer Science", name: "Numerical Analysis" },
  { code: "cs.NE", group: "Computer Science", name: "Neural and Evolutionary Computing" },
  { code: "cs.NI", group: "Computer Science", name: "Networking and Internet Architecture" },
  { code: "cs.OH", group: "Computer Science", name: "Other Computer Science" },
  { code: "cs.OS", group: "Computer Science", name: "Operating Systems" },
  { code: "cs.PF", group: "Computer Science", name: "Performance" },
  { code: "cs.PL", group: "Computer Science", name: "Programming Languages" },
  { code: "cs.RO", group: "Computer Science", name: "Robotics" },
  { code: "cs.SC", group: "Computer Science", name: "Symbolic Computation" },
  { code: "cs.SD", group: "Computer Science", name: "Sound" },
  { code: "cs.SE", group: "Computer Science", name: "Software Engineering" },
  { code: "cs.SI", group: "Computer Science", name: "Social and Information Networks" },
  { code: "cs.SY", group: "Computer Science", name: "Systems and Control" },
  { code: "econ.EM", group: "Economics", name: "Econometrics" },
  { code: "econ.GN", group: "Economics", name: "General Economics" },
  { code: "econ.TH", group: "Economics", name: "Theoretical Economics" },
  { code: "eess.AS", group: "Electrical Engineering and Systems Science", name: "Audio and Speech Processing" },
  { code: "eess.IV", group: "Electrical Engineering and Systems Science", name: "Image and Video Processing" },
  { code: "eess.SP", group: "Electrical Engineering and Systems Science", name: "Signal Processing" },
  { code: "eess.SY", group: "Electrical Engineering and Systems Science", name: "Systems and Control" },
  { code: "math.AC", group: "Mathematics", name: "Commutative Algebra" },
  { code: "math.AG", group: "Mathematics", name: "Algebraic Geometry" },
  { code: "math.AP", group: "Mathematics", name: "Analysis of PDEs" },
  { code: "math.AT", group: "Mathematics", name: "Algebraic Topology" },
  { code: "math.CA", group: "Mathematics", name: "Classical Analysis and ODEs" },
  { code: "math.CO", group: "Mathematics", name: "Combinatorics" },
  { code: "math.CT", group: "Mathematics", name: "Category Theory" },
  { code: "math.CV", group: "Mathematics", name: "Complex Variables" },
  { code: "math.DG", group: "Mathematics", name: "Differential Geometry" },
  { code: "math.DS", group: "Mathematics", name: "Dynamical Systems" },
  { code: "math.FA", group: "Mathematics", name: "Functional Analysis" },
  { code: "math.GM", group: "Mathematics", name: "General Mathematics" },
  { code: "math.GN", group: "Mathematics", name: "General Topology" },
  { code: "math.GR", group: "Mathematics", name: "Group Theory" },
  { code: "math.GT", group: "Mathematics", name: "Geometric Topology" },
  { code: "math.HO", group: "Mathematics", name: "History and Overview" },
  { code: "math.IT", group: "Mathematics", name: "Information Theory" },
  { code: "math.KT", group: "Mathematics", name: "K-Theory and Homology" },
  { code: "math.LO", group: "Mathematics", name: "Logic" },
  { code: "math.MG", group: "Mathematics", name: "Metric Geometry" },
  { code: "math.MP", group: "Mathematics", name: "Mathematical Physics" },
  { code: "math.NA", group: "Mathematics", name: "Numerical Analysis" },
  { code: "math.NT", group: "Mathematics", name: "Number Theory" },
  { code: "math.OA", group: "Mathematics", name: "Operator Algebras" },
  { code: "math.OC", group: "Mathematics", name: "Optimization and Control" },
  { code: "math.PR", group: "Mathematics", name: "Probability" },
  { code: "math.QA", group: "Mathematics", name: "Quantum Algebra" },
  { code: "math.RA", group: "Mathematics", name: "Rings and Algebras" },
  { code: "math.RT", group: "Mathematics", name: "Representation Theory" },
  { code: "math.SG", group: "Mathematics", name: "Symplectic Geometry" },
  { code: "math.SP", group: "Mathematics", name: "Spectral Theory" },
  { code: "math.ST", group: "Mathematics", name: "Statistics Theory" },
  { code: "astro-ph.CO", group: "Physics", name: "Cosmology and Nongalactic Astrophysics" },
  { code: "astro-ph.EP", group: "Physics", name: "Earth and Planetary Astrophysics" },
  { code: "astro-ph.GA", group: "Physics", name: "Astrophysics of Galaxies" },
  { code: "astro-ph.HE", group: "Physics", name: "High Energy Astrophysical Phenomena" },
  { code: "astro-ph.IM", group: "Physics", name: "Instrumentation and Methods for Astrophysics" },
  { code: "astro-ph.SR", group: "Physics", name: "Solar and Stellar Astrophysics" },
  { code: "cond-mat.dis-nn", group: "Physics", name: "Disordered Systems and Neural Networks" },
  { code: "cond-mat.mes-hall", group: "Physics", name: "Mesoscale and Nanoscale Physics" },
  { code: "cond-mat.mtrl-sci", group: "Physics", name: "Materials Science" },
  { code: "cond-mat.other", group: "Physics", name: "Other Condensed Matter" },
  { code: "cond-mat.quant-gas", group: "Physics", name: "Quantum Gases" },
  { code: "cond-mat.soft", group: "Physics", name: "Soft Condensed Matter" },
  { code: "cond-mat.stat-mech", group: "Physics", name: "Statistical Mechanics" },
  { code: "cond-mat.str-el", group: "Physics", name: "Strongly Correlated Electrons" },
  { code: "cond-mat.supr-con", group: "Physics", name: "Superconductivity" },
  { code: "gr-qc", group: "Physics", name: "General Relativity and Quantum Cosmology" },
  { code: "hep-ex", group: "Physics", name: "High Energy Physics - Experiment" },
  { code: "hep-lat", group: "Physics", name: "High Energy Physics - Lattice" },
  { code: "hep-ph", group: "Physics", name: "High Energy Physics - Phenomenology" },
  { code: "hep-th", group: "Physics", name: "High Energy Physics - Theory" },
  { code: "math-ph", group: "Physics", name: "Mathematical Physics" },
  { code: "nlin.AO", group: "Physics", name: "Adaptation and Self-Organizing Systems" },
  { code: "nlin.CD", group: "Physics", name: "Chaotic Dynamics" },
  { code: "nlin.CG", group: "Physics", name: "Cellular Automata and Lattice Gases" },
  { code: "nlin.PS", group: "Physics", name: "Pattern Formation and Solitons" },
  { code: "nlin.SI", group: "Physics", name: "Exactly Solvable and Integrable Systems" },
  { code: "nucl-ex", group: "Physics", name: "Nuclear Experiment" },
  { code: "nucl-th", group: "Physics", name: "Nuclear Theory" },
  { code: "physics.acc-ph", group: "Physics", name: "Accelerator Physics" },
  { code: "physics.ao-ph", group: "Physics", name: "Atmospheric and Oceanic Physics" },
  { code: "physics.app-ph", group: "Physics", name: "Applied Physics" },
  { code: "physics.atm-clus", group: "Physics", name: "Atomic and Molecular Clusters" },
  { code: "physics.atom-ph", group: "Physics", name: "Atomic Physics" },
  { code: "physics.bio-ph", group: "Physics", name: "Biological Physics" },
  { code: "physics.chem-ph", group: "Physics", name: "Chemical Physics" },
  { code: "physics.class-ph", group: "Physics", name: "Classical Physics" },
  { code: "physics.comp-ph", group: "Physics", name: "Computational Physics" },
  { code: "physics.data-an", group: "Physics", name: "Data Analysis, Statistics and Probability" },
  { code: "physics.ed-ph", group: "Physics", name: "Physics Education" },
  { code: "physics.flu-dyn", group: "Physics", name: "Fluid Dynamics" },
  { code: "physics.gen-ph", group: "Physics", name: "General Physics" },
  { code: "physics.geo-ph", group: "Physics", name: "Geophysics" },
  { code: "physics.hist-ph", group: "Physics", name: "History and Philosophy of Physics" },
  { code: "physics.ins-det", group: "Physics", name: "Instrumentation and Detectors" },
  { code: "physics.med-ph", group: "Physics", name: "Medical Physics" },
  { code: "physics.optics", group: "Physics", name: "Optics" },
  { code: "physics.plasm-ph", group: "Physics", name: "Plasma Physics" },
  { code: "physics.pop-ph", group: "Physics", name: "Popular Physics" },
  { code: "physics.soc-ph", group: "Physics", name: "Physics and Society" },
  { code: "physics.space-ph", group: "Physics", name: "Space Physics" },
  { code: "quant-ph", group: "Physics", name: "Quantum Physics" },
  { code: "q-bio.BM", group: "Quantitative Biology", name: "Biomolecules" },
  { code: "q-bio.CB", group: "Quantitative Biology", name: "Cell Behavior" },
  { code: "q-bio.GN", group: "Quantitative Biology", name: "Genomics" },
  { code: "q-bio.MN", group: "Quantitative Biology", name: "Molecular Networks" },
  { code: "q-bio.NC", group: "Quantitative Biology", name: "Neurons and Cognition" },
  { code: "q-bio.OT", group: "Quantitative Biology", name: "Other Quantitative Biology" },
  { code: "q-bio.PE", group: "Quantitative Biology", name: "Populations and Evolution" },
  { code: "q-bio.QM", group: "Quantitative Biology", name: "Quantitative Methods" },
  { code: "q-bio.SC", group: "Quantitative Biology", name: "Subcellular Processes" },
  { code: "q-bio.TO", group: "Quantitative Biology", name: "Tissues and Organs" },
  { code: "q-fin.CP", group: "Quantitative Finance", name: "Computational Finance" },
  { code: "q-fin.EC", group: "Quantitative Finance", name: "Economics" },
  { code: "q-fin.GN", group: "Quantitative Finance", name: "General Finance" },
  { code: "q-fin.MF", group: "Quantitative Finance", name: "Mathematical Finance" },
  { code: "q-fin.PM", group: "Quantitative Finance", name: "Portfolio Management" },
  { code: "q-fin.PR", group: "Quantitative Finance", name: "Pricing of Securities" },
  { code: "q-fin.RM", group: "Quantitative Finance", name: "Risk Management" },
  { code: "q-fin.ST", group: "Quantitative Finance", name: "Statistical Finance" },
  { code: "q-fin.TR", group: "Quantitative Finance", name: "Trading and Market Microstructure" },
  { code: "stat.AP", group: "Statistics", name: "Applications" },
  { code: "stat.CO", group: "Statistics", name: "Computation" },
  { code: "stat.ME", group: "Statistics", name: "Methodology" },
  { code: "stat.ML", group: "Statistics", name: "Machine Learning" },
  { code: "stat.OT", group: "Statistics", name: "Other Statistics" },
  { code: "stat.TH", group: "Statistics", name: "Statistics Theory" }
];

const knownCodes = new Set(ARXIV_CATEGORIES.map((category) => category.code));
const arxivCodePattern = /^[a-z-]+(\.[A-Z]{2})?$/;

export function isValidArxivCategory(code: string, allowAdvanced = true) {
  const trimmed = code.trim();
  if (knownCodes.has(trimmed)) return true;
  return allowAdvanced && arxivCodePattern.test(trimmed);
}

export function validateArxivCategories(codes: string[], allowAdvanced = true) {
  const unique = Array.from(new Set(codes.map((code) => code.trim()).filter(Boolean)));
  const invalid = unique.filter((code) => !isValidArxivCategory(code, allowAdvanced));
  return {
    ok: invalid.length === 0,
    valid: unique.filter((code) => !invalid.includes(code)),
    invalid
  };
}

export function getSubscriptionUnion(userCategoryLists: string[][]) {
  return Array.from(new Set(userCategoryLists.flat().map((code) => code.trim()).filter(Boolean))).sort();
}
